# Generated by Django 5.1.4 on 2025-01-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/sarmhi/image/upload/v1735955015/qnakd2blcdwagxlrkkqw.png', upload_to=''),
            preserve_default=False,
        ),
    ]
