# Generated by Django 5.1.4 on 2025-01-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='others',
        ),
    ]
