# Generated by Django 5.1.4 on 2025-01-11 23:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blog_created_at_blog_updated_at_category_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('job_location', models.CharField(choices=[('onsite', 'Onsite'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20)),
                ('job_type', models.CharField(choices=[('fulltime', 'Full-Time'), ('parttime', 'Part-Time'), ('contract', 'Contract')], max_length=20)),
                ('application_link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='talent',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='talent_partners', to='api.partner'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='works',
            field=models.ManyToManyField(blank=True, related_name='talent_works', to='api.work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='work_partners', to='api.partner'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.talent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
