# Generated by Django 3.2.20 on 2025-05-16 13:36

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_job_alter_talent_partners_alter_talent_works_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
